### ISSUE TITLE
B5st + Woocommerce

### ISSUE THREAD

**Issue by geekabit** [SimonPadbury/b5st#3]
I`m trying to make this team support Woocommerce which should be super easy but after declaring support i get no images on the product site. It doesnt happen with b4st. Do you know what can be the reason?

**Comment by SimonPadbury** [comment]
Hi Geekabit,

Sorry for the delay — I had no time until now (Saturday).

Here's what I've just done. Simplest setup, not quite following my b4st wiki but close — looks like the order of setting up is wrong in https://github.com/SimonPadbury/b4st/wiki/Adding-WooCommerce-support-to-b4st 

This works for me in b5st:

1. Fresh WordPress install on a local server (I started over, with a new project in Flywheel Local).

2. Install and activate the WooCommerce plugin — skip whatever you don't need at this stage.

3. Paste `b5st/` (unzipped) into the WordPress `themes/` folder.
 
> Don't activate theme b5st yet, because it's not WooCommerce-ready, until you've added Woocommerce support._ Instead, open it as a project in an editor (e.g. VS Code).

4. In b5st’s `functions/setup.php` , _inside_ `function b5st_setup() { ......}` , I simply pasted in `add_theme_support( 'woocommerce' );` (But you could do what I said in the b4st wiki.)

5. in b5st's root folder, create `woocommerce.php` and paste into it this basic template:

```
<?php get_header(); ?>

<div class="container mt-5">
  <div id="content" role="main">

    <?php woocommerce_content(); ?>

  </div><!-- /#content -->
</div><!-- /.container-responsive -->

<?php get_footer(); ?>
``` 

6. Now, in Appearance>Themes, _Activate_ b5st. This will now initiate correctly as a WooCommerce-ready theme, because you did the stuff above.

6. Populate the navbar.

7. Inside the WooCommerce plugin folder, there's a folder called `sample-data/`. Using the `sample_products.csv` you’ll find there, do this: https://woocommerce.com/document/importing-woocommerce-sample-data/

8. View the site frontend (refresh it), and you've got demo merch with images.
